### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by dorthwein** [rastapasta/react-native-gl-model-view#1]
@rastapasta - great work on this.  We're looking at using it for our mobile app and potentially contributing with the Android Port.

Do you have any suggestions or guidance on what (if any) Android libs you'd like to use to map the native bindings to?

**Comment by rastapasta** [comment]
Hey @dorthwein - thanks for the feedback, I'm excited to hear your plans!

I came across the [jPCT 3D engine](http://www.jpct.net/jpct-ae/) for Android, which has a very low profile and very active community. Key features which would make it a good match (c&p from its page):

* free
* OpenGL ES 1.x and 2.0 on Android >=1.5
* loads 3DS, OBJ, MD2, ASC and serialized files

Cheers + looking forward to your ideas

**Comment by HofmannZ** [comment]
Any updates regarding android support, would like to help, not an Android pro though ..

**Comment by dorthwein** [comment]
@rastapasta - we'd be willing to pay you to implement Android Support if you'd do it in a timely manner and reasonably priced ;)

**Comment by PatriceVignola** [comment]
Hey guys, I made a [PR for the Android Support](https://github.com/rastapasta/react-native-gl-model-view/pull/5) since I needed it for my own project and open source sharing is awesome :) Even though the primary goal was to support my project, feel free to leave comments, suggest improvements or file bugs.

**Comment by rastapasta** [comment]
@PatriceVignola, great to hear from you and thank you for this early x-mas present to the community! :gift: 
Will fly over it and am looking more than forward to hitting the merge button! 

Welcome on board :beers:

**Comment by vutiendat88** [comment]
Hello!

I'm waiting for the android support version. Let me know anything for it to be released as soon as possible

**Comment by rastapasta** [comment]
@vutiendat88 just got merged into master and pushed to npm as v1.1
Some slight updates will follow to the example - trying out @PatriceVignola 's work was pure joy!

**Comment by vutiendat88** [comment]
@PatriceVignola  Line 20 of RNGLModelViewPackage.java remove @Override 
This method does not override or implement a method from a supertype
Chear!

**Comment by PatriceVignola** [comment]
The createJSModules() method was removed in react-native 0.47, but the peerDependencies in react-native-gl-model-view's package.json specifies react-native >= 0.41. If we remove the @override, the module will stop working for versions >= 0.41 and < 0.47.

I believe it's a good idea to update the dependency to the latest version, but when I tried it, it broke too many things not related to my changes. Therefore, it would be better to create another bug or task that would take care of updating the whole package to the latest react-native version. In the meantime, it will work when using react-native version < 0.47. Maybe we should hotfix package.json to only allow react-native between 0.41 and 0.47 (exclusive)?

What do you think @rastapasta ?

**Comment by vutiendat88** [comment]
@PatriceVignola How to use .obj in it? Can you help me with an example of usage?

**Comment by PatriceVignola** [comment]
Hey everyone (especially @vutiendat88)! I updated the module to support react-native >=0.47. I created a pull request over [here](https://github.com/rastapasta/react-native-gl-model-view/pull/8). You can give it a look if you want and pull my branch to make sure it's working on your system. Don't hesitate to contact me if you have any problems. I faced a lot of problems myself during the lengthy upgrade process so I can probably help you out. I will be babysitting this PR in the following days/weeks and make sure to make changes if you guys have issues.

**Comment by rastapasta** [comment]
Awesome news, tested, verrry happy, merged and pushed to NPM as 1.2.0! Thank you!
