### ISSUE TITLE
How can i add material (.mtl) file with .obj model?

### ISSUE THREAD

**Issue by harisanwar64** [rastapasta/react-native-gl-model-view#18]
I have successfully build model using 'react-native-gl-model-view' and loaded my object file (.obj) in my react native app. I need to add material on my model with .mtl file. how can i load and use .mtl file with .obj? Is 'react-native-gl-model-view' have support for .mtl?

**Comment by PatriceVignola** [comment]
It does not have support for .mtl files unfortunately.

**Comment by harisanwar64** [comment]
@PatriceVignola any alternative to do clicking on model part/object and get some value returned from it(Raycasting)?
