### ISSUE TITLE
Draw vertices and lines with .obj model

### ISSUE THREAD

**Issue by Morphinity** [rastapasta/react-native-gl-model-view#19]
Hi,
Beginner at using .obj files here. I am attempting to draw some vertices and connecting them with lines (kind of like a 3D wireframe model). My .obj file looks like this - 

sample.obj
```
v 0 0 0
v 1 0 0
v 1 1 0
v 0 1 0
f 1 2 3 4
v 0 0 1
l 1 5
v 1 0 1
v 1 1 1
l 3 7
v 0 1 1
f 5 6 7 8
l 4 8
l 2 6 
```

Component
```
<ModelView
          model="sample.obj"
          texture="texture.png"

          scale={1}

          translateZ={-2}
          rotateZ={45}
          style={{flex: 1}}
        />
```
It's basically a cube with two faces connected by lines. When I load the model, nothing gets drawn.

Is it in inherent limitation of .obj files to not draw vertices and lines between them or am I missing something?

**Comment by rastapasta** [comment]
Heya @Morphinity - sorry for the late reply. Please make sure that the object renders as expected in any other editor or viewer to check its validity and rendering. Closing this issue for now, cheers!
