### ISSUE TITLE
How to get the *.model file?

### ISSUE THREAD

**Issue by DoubleWoodH** [rastapasta/react-native-gl-model-view#21]
Hi, I am getting an error, I think I lack the *.model file, but I don't know how to get it?
![image](https://user-images.githubusercontent.com/20528848/53719506-3a448c00-3e99-11e9-9c1a-162588564a44.png)

**Comment by PatriceVignola** [comment]
You can get the .model file from [the examples](https://github.com/rastapasta/react-native-gl-model-view/tree/master/example/data).
