### ISSUE TITLE
model and texture files not working

### ISSUE THREAD

**Issue by Amjad675** [rastapasta/react-native-gl-model-view#22]
Everything has been linked and works fine without any linking issues. But when I pass the model and texture props to ModelView as below
model={{
                uri: "cmodel.obj"
              }}
              texture={{
                uri: "texture.png"
              }}

I get the following error (screenshot attached)

Can somebody please assist me on this? 
![Screen Shot 2019-04-10 at 6 25 09 PM](https://user-images.githubusercontent.com/26712217/55880364-2b4ea900-5bbe-11e9-89bc-3d7b5400568c.png)

**Comment by rastapasta** [comment]
Dear @Amjad675, you were faster than me :)

Just pushed the new version (with the new URI scheme) to NPM as v1.4 - could you check if you are on the correct version?

Cheers!

**Comment by Amjad675** [comment]
Hi @rastapasta Thanks for the update.

There is no error like before. But I do get a warning for failed prop type for model and texture. As a result the 3D object is not rendered.. Any reason as to why?

Is there any specific way you pass the URI to the model and texture? The .model and .png files are in the root of the xcode project too.
model={{
                uri: "demon.model"
              }}
              texture={{
                uri: "demon.png"
              }}

![Screen Shot 2019-04-10 at 8 21 40 PM](https://user-images.githubusercontent.com/26712217/55889366-9dc78500-5bce-11e9-876e-1c76b85a672a.png)
![Screen Shot 2019-04-10 at 8 21 52 PM](https://user-images.githubusercontent.com/26712217/55889368-9dc78500-5bce-11e9-936c-036411988598.png)

**Comment by Dylan-at-LION** [comment]
@Amjad675 You don't need the `{ uri: ... }` just try `model={'demon.model'}` and `texture={'demon.png'}`

**Comment by Amjad675** [comment]
I removed the node_modules folder and ran npm install again and the issue was solved.. I did not change the structure of model and texture.. Kept them as below and worked flawlessly 😍 

model={{
            uri: "demon.obj"
          }}
          texture={{
            uri: "demon.png"
          }}

Thank you so much @rastapasta for the support :) Appreciate your hard work! Keep it up 👍 
![Screenshot_2](https://user-images.githubusercontent.com/26712217/55930168-c175e400-5c3d-11e9-9cd8-e5870c80aa7e.jpg)
