### ISSUE TITLE
Release build failing

### ISSUE THREAD

**Issue by Amjad675** [rastapasta/react-native-gl-model-view#23]
While building a production release (1st time) I get an error. But works fine on development environment. Can @rastapasta @PatriceVignola @Cawfree you please guide me on this and let me know what the issue is?

> Task :react-native-gl-model-view:verifyReleaseResources FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gl-model-view:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  ..\node_modules\react-native-gl-model-view\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  ..\node_modules\react-native-gl-model-view\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  ..\node_modules\react-native-gl-model-view\android\build\intermediates\res\merged\release\values\values.xml:2714: error: resource android:attr/fontVariationSettings not found.
  ..\node_modules\react-native-gl-model-view\android\build\intermediates\res\merged\release\values\values.xml:2715: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

![Error](https://user-images.githubusercontent.com/26712217/56713379-41786f80-674f-11e9-9eb8-aa1dfe36e86e.jpg)

**Comment by Cawfree** [comment]
Hi @Amjad675 , I believe this could be related to your [`compileSdkVersion`](https://stackoverflow.com/questions/49280632/error9-5-error-resource-androidattr-dialogcornerradius-not-found).

**Comment by Amjad675** [comment]
Thanks for the reply @Cawfree Below is my android/build.gradle file. What do you recommend for a fix?

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

**Comment by Amjad675** [comment]
Thanks for the reply @Cawfree  I was able to figure out the issue. Unfortunately the android/build.gradle file of react-native-gl-model-view has compileSdkVersion set to 27 which is the cause for the issue. Once I edited it to compileSdkVersion rootProject.hasProperty('compileSdkVersion') ? rootProject.compileSdkVersion : 28 it built successfully. 

Can the contributors kindly update the android/build.gradle file so that we won't have to come across this issue again? @rastapasta @PatriceVignola

**Comment by rastapasta** [comment]
Aloha @Amjad675 & @cawfree - thanks a lot for checking in!

The ```build.gradle``` [got updated](https://github.com/rastapasta/react-native-gl-model-view/blob/master/android/build.gradle#L13-L14) accordingly and will be included in the next release tonight. Cheers!
