### ISSUE TITLE
error while loading model

### ISSUE THREAD

**Issue by nickwansi** [rastapasta/react-native-gl-model-view#25]
Please, i need help. I'm getting the error while trying **rastapasta/react-native-gl-model-view** code " .  Other .obj files are working well but my 3d.obj is not working....
![Screenshot_20190522-185219](https://user-images.githubusercontent.com/46792467/58214451-c067b600-7cc3-11e9-81f1-a67f75ec45c8.png)

**Comment by rastapasta** [comment]
Sorry, can't reproduce.
