### ISSUE TITLE
Remove Axial Tilt from 3D Model in Android?

### ISSUE THREAD

**Issue by Malikkhoja** [rastapasta/react-native-gl-model-view#32]
Hi @PatriceVignola @rastapasta ,

I am new to developing 3D models in react native. I am able to rotate the 3D Model in both IOS and Android. However, the 3D model uses the axial tilt by default in android and changes its axis/position and the same works perfect in IOS.

Can you help me removing the axial tilt from 3D model in Android?

Thanks in Advance

**Comment by rastapasta** [comment]
Dear @Malikkhoja 

there was a slight issue with the rotation working a bit different on both platforms - please check again, v1.6.0 addressed these.

Closing the issue for now, happy to reopen it as soon as you were able to confirm. Bests!
