### ISSUE TITLE
"RNGLModelView" was not found in the UIManager

### ISSUE THREAD

**Issue by edmsamuel** [rastapasta/react-native-gl-model-view#33]
Hi, i'm on Windows 10 and macOS too, please how can i fit it???

![image](https://user-images.githubusercontent.com/14112893/70283720-d16fa480-1787-11ea-90ff-bc8184321876.png)

**Comment by rastapasta** [comment]
Please make sure to follow the [README](https://github.com/rastapasta/react-native-gl-model-view#getting-started) on how to correctly include the library. Cheers!

**Comment by edmsamuel** [comment]
I need to eject de expo project?

**Comment by krjk333** [comment]
@rastapasta I did the same in the documentation requirement for android.  But still the same issue.  How to fix it
