### ISSUE TITLE
In android, the model loads above everything!

### ISSUE THREAD

**Issue by Malikkhoja** [rastapasta/react-native-gl-model-view#35]
![Screenshot_1578651681](https://user-images.githubusercontent.com/5652900/72145703-127b5a00-33c1-11ea-9d8f-fc63185729e0.png)

@rastapasta  ,I am basically trying to show a text view over the model.However the model actually loads in a weird way which is at a very high elevation.
Could you please look into it and help me with a solution or any approach to resolve the same?

**Comment by rastapasta** [comment]
Heya @Malikkhoja, thanks for checking in!
The issue just got fixed in v.1.6.0 by the changes made by @reyalpsirc ✨
