### ISSUE TITLE
Objects not showing

### ISSUE THREAD

**Issue by Lypzis** [rastapasta/react-native-gl-model-view#37]
It seem that objects other than the "demon.obj"  aren't rendering at all, I'm curious to know what might cause it, and what did you use to generate the "demon.obj", since it is the only one that works.

And yep, followed all instructions of the docs, only the demon shows up, anything else does not.

the piece:
`return (
		<View style={styles.container}>
			<ModelView
				model={{ uri: "demon.obj" }}
				tint={{ r: 0.3, g: 0.1, b: 1, a: 1 }}
				scale={0.01}
				translateZ={-4}
				rotateZ={240}
				rotateY={100}
				style={{ width: "100%", height: "50%" }}
			/>
		</View>
	);`

**Comment by rastapasta** [comment]
Dear @Lypzis, thanks for checking in. I just tried some random objs from the internets ([example](http://www.cadnav.com/3d-models/model-49237.html)) and had no issue at all on both platforms. Additionally experimented with Blender's wavefront export and had no problem either (on the simple objects me no-3d-dude was able to create ;) ).

Make sure to experiment with the translateZ and scale parameters on unknown wavefronts which might be scaled oddly.

Good luck, closing for now but am happy to reopen at any time.
