### ISSUE TITLE
Problem displaying model

### ISSUE THREAD

**Issue by Muhamman78** [rastapasta/react-native-gl-model-view#38]

**Comment by rastapasta** [comment]
> I can't open the model or texture when i store it locally.I have viewed your read me and i have written the same exact code. It works fine for your model but it is not working when i use any other model or obj file,  it shows a blank screen  

Please make sure to
* include it in your project (android: assets folder, iOS: via Xcode)
* if included, try to scale it down, set translateZ to -10 to check if it might just be too big

Just checked with different wavefront objs and had no issue. Good luck!
