### ISSUE TITLE
Example installs node_modules twice

### ISSUE THREAD

**Issue by zachgibson** [rastapasta/react-native-gl-model-view#4]
Running `npm i` in `example/` installs the local `react-native-gl-model-view` but it doesn’t ignore `example/` directory which results in a duplicate module error.

e.g. `example/node_modules/react-native-gl-model-view/example/node_modules`

**Comment by rastapasta** [comment]
Hey @zachgibson, fixed with the latest release and @PatriceVignola 's introduction to `install-local` in the updated [readme](https://github.com/rastapasta/react-native-gl-model-view#examples) - cheers!
