### ISSUE TITLE
Adding .fbx files for animation?

### ISSUE THREAD

**Issue by craftmusic** [rastapasta/react-native-gl-model-view#40]
Is there a way the models can be animated with .fbx files specific to the model?

**Comment by rastapasta** [comment]
Heya @craftmusic, thanks for checking in - at the current state, it's not possible. Sadly wise this most likely will keep that way. While the Android side of things (implemented from scratch with jPCT-AE by @PatriceVignola  ✨) is much more flexible, the upstream, unmaintained GLView would most likely need a rewrite (especially as it already support fewer formats than the Android part). Cheers!

**Comment by craftmusic** [comment]
@rastapasta is it possible in react native though? If so, can I hire you to do it? I can tell you more about what I’m trying to do if you email me at info@craftmusicapp.com
