### ISSUE TITLE
facing issue in android with error message " Invariant Violation: requireNativeComponent: "RNGLModelView" was not found in the UIManager."

### ISSUE THREAD

**Issue by krjk333** [rastapasta/react-native-gl-model-view#53]
I done all the required steps in documentation.  But still I am facing the issue like below. 
```
 ERROR    Invariant Violation: requireNativeComponent: "RNGLModelView" was not found in the UIManager.
This error is located at:
    in RNGLModelView (at react-native-gl-model-view/index.js:7)
    in GLModelView (at App.js:8)
    in Cat (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
```

**Comment by krjk333** [comment]
Based on the documentation, we have to do some manual changes in android/app/build.gradle and and android/settings.gradle , but the example shared in github doesn't having those changes  https://github.com/rastapasta/react-native-gl-model-view/tree/master/example/android .  So actually what should I do.  Should I add those changes or not? Please say solution

**Comment by dlarch21** [comment]
Having same issue did you find a solution ?

**Comment by rastapasta** [comment]
There are no changes needed to any of the gradle files if you use RN >0.60 which implemented autolinking. The README will be updated accordingly.
