### ISSUE TITLE
Not compatible with React-Native 0.65.1

### ISSUE THREAD

**Issue by npjoge** [rastapasta/react-native-gl-model-view#59]
My app is comfortable with **RN- 0.63.4**
But once I have upgrade **RN lib to 0.65.1**, facing issue in android with error message "ConnectAnimatedNodes: Animated node with tag does not exist" when using **useNativeDriver** is true.

**Comment by tradebulls** [comment]
@rastapasta Can you please help?

**Comment by rastapasta** [comment]
Aloha together - I'm unable to reproduce this on v0.67.1. Just updated the example project - could you check if the error persists for you?
