### ISSUE TITLE
RNGLModelView does not exist

### ISSUE THREAD

**Issue by ankitbisht143** [rastapasta/react-native-gl-model-view#6]
I am getting error on importing ModelView that Native component for 'RNGLModelView' does not exist

**Comment by barend4i** [comment]
@ankitbisht143 getting the same, have you found a solution yet?

**Comment by PatriceVignola** [comment]
Is it happening only for Android, for iOS, or for both? Also, did you do the `react-native link` command? Usually, this error happens when the native project hasn't been properly linked to the project.

**Comment by godofmadness** [comment]
struggling the same issue, lib was linked in podfile.

**Comment by RadiksMan** [comment]
Same issues (linked lib without pods)

**Comment by Amjad675** [comment]
You need to install cocopods to ensure this library works.

1) Run brew install cocoapods in your terminal
2) Inside your iOS folder, run pod init
3) Once the podfile is generated, you should get a file with the below content

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '<project-name>' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for <project-name>
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNGLModelView', :path => '../node_modules/react-native-gl-model-view'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end

4) Now run the following 2 commands
 npm i react-native-gl-model-view --save and react-native link react-native-gl-model-view
5) Go back to your iOS folder and now run pod install
6) Open the application using the file <project-name>.xcworkspace and do a clean and build

And your application should work now.. Hope it helps! :)

**Comment by rastapasta** [comment]
Closing due to perfect documentation by @Amjad675 (thanks for that!) and autolinking from RN >= 0.60

**Comment by edmsamuel** [comment]
hi i have the same problem on windows, how can i fix it

![image](https://user-images.githubusercontent.com/14112893/70064440-299f7e80-15af-11ea-941c-2b8b6ac8803c.png)

**Comment by krjk333** [comment]
I am facing this issue in android, please help me anyone
